name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update System
      run: sudo apt-get update
    - name: Install javafx
      run: sudo apt update sudo apt install openjdk-8-jdk \ openjdk-8-jre \ openjfx
    - name: Java Version
      run: java -version
    - name: Build with Maven
      run: mvn jfx:jar
