name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Update System
      run: sudo apt-get update
    - name: Install javafx
      run: sudo apt install \ openjfx=8u161-b12-1ubuntu2 \ libopenjfx-java=8u161-b12-1ubuntu2 \ libopenjfx-jni=8u161-b12-1ubuntu2
    - name: Verify Installation
      run: sudo apt-mark hold openjfx \ libopenjfx-java \ libopenjfx-jni
    - name: Build with Maven
      run: mvn jfx:jar
